services:
  web:
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/html
      - ./server:/var/www/server
      - ./ftp:/ftp
    depends_on:
      db:
        condition: service_healthy
      ftp:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stay_app
      MYSQL_USER: stay_user
      MYSQL_PASSWORD: stay_pass
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  ftp:
    image: fauria/vsftpd
    ports:
      - '21:21'
      - '21000-21010:21000-21010'
    environment:
      FTP_USER: user
      FTP_PASS: pass
      PASV_ADDRESS: ftp
      PASV_MIN_PORT: 21000
      PASV_MAX_PORT: 21010
    volumes:
      - ./ftp:/home/user
    healthcheck:
      test: ['CMD', 'curl', '-f', '-u', 'user:pass', 'ftp://localhost/']
      interval: 10s
      timeout: 5s
      retries: 5
